export enum AuthorityEnum {
    GRANT_AUTHORITY_TO_ROLE = "GRANT_AUTHORITY_TO_ROLE",
    REVOKE_AUTHORITY_FROM_ROLE = "REVOKE_AUTHORITY_FROM_ROLE",
    ASSIGN_ROLE_TO_USER = "ASSIGN_ROLE_TO_USER",
    CREATE_ROLE = "CREATE_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",
    DELETE_ROLE = "DELETE_ROLE",
    VIEW_ROLES = "VIEW_ROLES",
    UPDATE_USERS = "UPDATE_USERS",
    VIEW_USERS = "VIEW_USERS",
    DELETE_USERS = "DELETE_USERS",
    VIEW_AUTHORITIES = "VIEW_AUTHORITIES",
  }
  